#pragma once

#include <sds.h>
#include <assert.h>
#include <stdio.h>

sds par_token_to_sds(par_token token);
par_buffer* par_buffer_from_path(const char* filepath);
sds par_asset_whereami();
void par_asset_set_baseurl(const char* url);
sds par_asset_baseurl();
int par_asset_fileexists(sds fullpath);
int par_asset_download(const char* filename, sds targetpath);
par_buffer* par_asset_to_buffer(par_token id);
void par_write_message(const char* msg);

// This takes two human-readable strings: the key and the metadata. The key
// should not be generated by sprintf because it is used as a grouping key in
// systems like Sentry.  The metadata, on the other hand, can be unique.

#define par_verify(expr, exception_key, exception_metadata)                \
    if (!(expr)) {                                                         \
        if (exception_metadata) {                                          \
            printf("%s: %s\n", exception_key, (char*) exception_metadata); \
        } else {                                                           \
            printf("%s\n", exception_key);                                 \
        }                                                                  \
    }                                                                      \
    assert(expr);
