#include <assert.h>
#include <stdio.h>

// This takes two human-readable strings: the key and the metadata. The key
// should not be generated by sprintf because it is used as a grouping key in
// systems like Sentry.  The metadata, on the hand, can have unique data.

#define par_verify(expr, exception_key, exception_metadata)                \
    if (!(expr)) {                                                         \
        if (exception_metadata) {                                          \
            printf("%s: %s\n", exception_key, (char*) exception_metadata); \
        } else {                                                           \
            printf("%s\n", exception_key);                                 \
        }                                                                  \
    }                                                                      \
    assert(expr);
